- job:
    name: ansible-role-shade
    run: tests/test.yaml
    required-projects:
      - name: openstack-infra/shade
    roles:
      - zuul: openstack/ansible-role-shade

- job:
    name: ansible-role-shade-centos-7
    parent: ansible-role-shade
    nodeset: centos-7

- job:
    name: ansible-role-shade-fedora-27
    parent: ansible-role-shade
    nodeset: fedora-27

- job:
    name: ansible-role-shade-ubuntu-bionic
    parent: ansible-role-shade
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-shade-ubuntu-xenial
    parent: ansible-role-shade
    nodeset: ubuntu-xenial

- project:
    templates:
      - windmill-jobs-fedora-27
      - windmill-jobs-bionic
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-shade-centos-7
        - ansible-role-shade-fedora-27
        - ansible-role-shade-ubuntu-bionic
        - ansible-role-shade-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-shade-centos-7
        - ansible-role-shade-fedora-27
        - ansible-role-shade-ubuntu-xenial
        - tox-linters
