- job:
    name: ansible-role-shade-base
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    roles:
      - zuul: openstack/ansible-role-shade

# Testing for nodepool_install_method: pip
- job:
    name: ansible-role-shade
    parent: ansible-role-shade-base

- job:
    name: ansible-role-shade-fedora-latest
    parent: ansible-role-shade
    nodeset: fedora-latest

- job:
    name: ansible-role-shade-ubuntu-bionic
    parent: ansible-role-shade
    nodeset: ubuntu-bionic

# Testing for nodepool_install_method: git
- job:
    name: ansible-role-shade-src
    parent: ansible-role-shade-base
    required-projects:
      - name: openstack-infra/shade
    vars:
      shade_git_update: false
      shade_install_method: git

- job:
    name: ansible-role-shade-src-fedora-latest
    parent: ansible-role-shade-src
    nodeset: fedora-latest

- job:
    name: ansible-role-shade-src-ubuntu-bionic
    parent: ansible-role-shade-src
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-shade-fedora-latest
        - ansible-role-shade-ubuntu-bionic
        - ansible-role-shade-src-fedora-latest
        - ansible-role-shade-src-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-shade-fedora-latest
        - ansible-role-shade-ubuntu-bionic
        - ansible-role-shade-src-fedora-latest
        - ansible-role-shade-src-ubuntu-bionic
        - tox-linters
